[package]
cairo-version = "=2.7.0"
name = "example"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.16" }
openzeppelin_token = { git = "https://github.com/underware-gg/cairo-contracts", branch = "pistols" }
# openzeppelin_token = { path = "../../cairo-contracts" }

[dev-dependencies]
openzeppelin_test_common = { git = "https://github.com/underware-gg/cairo-contracts", branch = "pistols" }
# openzeppelin_test_common = { path = "../../cairo-contracts" }

[[target.dojo]]
