# Example configuration file for Torii
contracts = [
    # { type = "WORLD", address = "<WORLD_CONTRACT_ADDRESS>" },
    # { type = "ERC20", address = "<ERC20_CONTRACT_ADDRESS>" },
    { type = "ERC721", address = "0x2037ffbff6c96e5aba4f71c05bbe08acdeca0e5da39fc9ca46912b48e53186a" },
]
