[package]
name = "nft_combo"
version.workspace = true
edition.workspace = true

[dependencies]
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.20.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts", tag = "v0.20.0" }
graffiti = { git = "https://github.com/ponderingdemocritus/graffiti", rev = "bc569531791dbc71c6cd8d9bc154c34eedad31fe" }

[dev-dependencies]
cairo_test = "=2.9.2"

[lib]

# [[target.starknet-contract]]
# build-external-contracts = ["dojo::world::world_contract::world"]
