kind = "DojoModel"
class_hash = "0x35435c72ce7a795254dbf2d397332c26ea5022a67a3995a5b9beb2c05436be8"
original_class_hash = "0x35435c72ce7a795254dbf2d397332c26ea5022a67a3995a5b9beb2c05436be8"
abi = "manifests/dev/base/abis/models/oz_token-CoinConfig-5f4d1c18.json"
tag = "oz_token-CoinConfig"
qualified_path = "oz_token::models::coin_config::coin_config"
manifest_name = "oz_token-CoinConfig-5f4d1c18"

[[members]]
name = "coin_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "faucet_amount"
type = "u256"
key = false
