kind = "DojoModel"
class_hash = "0x70e25585a526c9cf07889647103ad37d3b33e95db6e25043d609283a248b3db"
original_class_hash = "0x70e25585a526c9cf07889647103ad37d3b33e95db6e25043d609283a248b3db"
abi = "manifests/dev/base/abis/models/oz_token-TokenConfig-2d52d04c.json"
tag = "oz_token-TokenConfig"
qualified_path = "oz_token::models::token_config::token_config"
manifest_name = "oz_token-TokenConfig-2d52d04c"

[[members]]
name = "token_address"
type = "ContractAddress"
key = true

[[members]]
name = "minter_contract_address"
type = "ContractAddress"
key = false

[[members]]
name = "minted_count"
type = "u256"
key = false
