kind = "DojoModel"
class_hash = "0x5feff6da881f2decb37d907b53122f72dc46f6c7399b1d50707dcf7a30d47d5"
original_class_hash = "0x5feff6da881f2decb37d907b53122f72dc46f6c7399b1d50707dcf7a30d47d5"
abi = "manifests/dev/base/abis/models/oz_token-DirectionsAvailable-3f68cee5.json"
tag = "oz_token-DirectionsAvailable"
qualified_path = "oz_token::models::starter::directions_available"
manifest_name = "oz_token-DirectionsAvailable-3f68cee5"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "directions"
type = "Array<Direction>"
key = false
