kind = "DojoContract"
class_hash = "0x101ab1c76fd01ddca5c17c703df544d956257b1ff1432c7914e27400d5377ed"
original_class_hash = "0x101ab1c76fd01ddca5c17c703df544d956257b1ff1432c7914e27400d5377ed"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/oz_token-character-7e2ce6f5.json"
reads = []
writes = []
init_calldata = []
tag = "oz_token-character"
systems = ["mint"]
manifest_name = "oz_token-character-7e2ce6f5"
