kind = "DojoContract"
class_hash = "0x68770540d2972223ed70bded7df09979f85e95fcecbd68d2c503e5f1922539c"
original_class_hash = "0x68770540d2972223ed70bded7df09979f85e95fcecbd68d2c503e5f1922539c"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/oz_token-cash-3d2ed65a.json"
reads = []
writes = []
init_calldata = []
tag = "oz_token-cash"
systems = [
    "mint",
    "faucet",
]
manifest_name = "oz_token-cash-3d2ed65a"
