kind = "DojoContract"
class_hash = "0x57f6a4854544a4966bbe3a802b7fdf3b1cca2fe9426f670596fbee04b431caa"
original_class_hash = "0x57f6a4854544a4966bbe3a802b7fdf3b1cca2fe9426f670596fbee04b431caa"
base_class_hash = "0x0"
abi = "manifests/dev/base/abis/contracts/oz_token-actions-63d87cac.json"
reads = []
writes = []
init_calldata = []
tag = "oz_token-actions"
systems = [
    "spawn",
    "move",
]
manifest_name = "oz_token-actions-63d87cac"
